version: '2'
services:
  control:
    container_name: jepsen-control
    build: ./control
    hostname: control
    stdin_open: true
    tty: true
    volumes:
      - ../:/jepsen
      - ./secret:/root/.ssh
    privileged: true
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
  node:
    container_name: jepsen-node
    build: ./node
    privileged: true
    volumes:
      - ./secret:/root/.ssh
  n1:
    extends: node
    container_name: jepsen-n1
    hostname: n1
  n2:
    extends: node
    container_name: jepsen-n2
    hostname: n2
  n3:
    extends: node
    container_name: jepsen-n3
    hostname: n3
  n4:
    extends: node
    container_name: jepsen-n4
    hostname: n4
  n5:
    extends: node
    container_name: jepsen-n5
    hostname: n5
